; NFC Scanner ESP
[platformio]
default_envs = esp32dev

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

monitor_speed = 115200
upload_speed = 921600

; Library dependencies
lib_deps = 
    adafruit/Adafruit PN532@^1.3.3
    bblanchon/ArduinoJson@^7.0.4

; Device-specific flags
; Override SCANNER_LOCATION per env 

build_flags =
    -DSCANNER_LOCATION=\"In Transit\"

; Build & Flash each one using:
; pio run -e [environment name e.g. jp] -t upload


[env:jit]
extends = env:esp32dev
build_flags =
    -DSCANNER_LOCATION=\"JIT\"

[env:jp]
extends = env:esp32dev
build_flags =
    -DSCANNER_LOCATION=\"Jurassic Park\"

[env:mal]
extends = env:esp32dev
build_flags =
    -DSCANNER_LOCATION=\"MAL\"