[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200 ; Sets baud rate to remove garbage from console

; N16R8 memory layout
board_build.arduino.memory_type = qio_opi
board_upload.flash_size = 16MB

; Force compiler to enable PSRAM and USB
build_flags =
    -DBOARD_HAS_PSRAM
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1

; Location of apriltag library for PlatformIO
lib_deps = https://github.com/raspiduino/apriltag-esp32.git